### PR TITLE
Bugfixes and added support for very long strings and extended number of cases

### PR DESCRIPTION
**Pull request by Elmervc**
- Fixes reading `layout_code` and `prod_name` which were swapped
- Fixes determining whether file is compressed (embedded in file header, not in version info)
- Add support for reading Extended Number of Cases Record
- Try to read case data until EOF when number of cases, or extended number of cases is below 0
- Add support for very long string values
- Use encoding set in document for reading data

### CODE REVIEW

**Comment by akbertram** [comment]
Looks great, many thanks!

Do you have any test files that include "very long" variables? If you can maybe put together a very simple .sav file and add a test, I'd be very happy to merge!

**Comment by Elmervc** [comment]
Test added :)

**Comment by Elmervc** [comment]
Please wait with merging this PR, I've some more fixes coming today or tomorrow.

**Comment by Elmervc** [comment]
It's ready for review/merge.

**Comment by Elmervc** [comment]
@akbertram Can you review/merge this one?

**Pull request merged**
